language: node_js
node_js:
  - "9"

sudo: required
services:
  - docker
  - mongodb

# Apparently mongodb needs some time to start
before_script:
  - sleep 15
script: yarn build

deploy:
  provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: master

cache:
  directories:
    - "node_modules"