language: node_js
node_js:
  - "9"
  - "8"

sudo: required
services:
  - docker
  - mongodb

# Apparently mongodb needs some time to start
before_script:
  - sleep 15
script: yarn build

after_success: docker build -t projecti .
cache:
  directories:
    - "node_modules"